config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  resources :articles do
    resources :comments
  end
  resources :tags
  resources :authors
  resources :author_sessions, only: [:new, :create, :destroy]
  get 'login' => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'

  

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments
	has_many :taggings
	has_many :tags, through: :taggings
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>"}
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	def tag_list
		self.tags.collect do |tag|
			tag.name
		end.join(", ")
	end

	def tag_list=(tags_string)
		tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
		new_or_found_tags = tag_names.collect {|name| Tag.find_or_create_by(name: name)}
		self.tags = new_or_found_tags
	end
end

app/models/author.rb
class Author < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :articles, through: :taggings

def tag_list
  self.taggings
end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
before_filter :require_login, except: [:index, :show]

	include ArticlesHelper
	def index
		@article = Article.all
	end

	def show
		@article = Article.find(params[:id])
		@comment = Comment.new
		@comment.article_id = @article_id
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
			#title: params[:article][:title],
			#body: params[:article][:body])
		@article.save

		flash.notice = "'#{@article.title}' Has Been Created"
		redirect_to article_path(@article)
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		flash.notice = "'#{@article.title}' Has Been Deleted."
		redirect_to articles_path
		
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		@article.update(article_params)

		flash.notice = "'#{@article.title}' Has Been Updated!"

		redirect_to article_path(@article)
	end
end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController

	def new
	end

	def create
		if login(params[:email], params[:password])
			redirect_back_or_to(articles_path, notice: 'Logged in successfully.')
		else
			flash.now.alert = "Login failed"
			render action: :new
		end
	end
	def destroy
		logout
		redirect_to(articles_path, notice: 'Logged out!')
	end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_filter :require_login, except: [:new, :create]
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end

    before_filter :zero_authors_or_authenticated, only: [:new, :create]

    def zero_authors_or_authenticated
      unless Author.count == 0 || current_user
        redirect_to root_path
        return false
      end
end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filer :require_login, except: [:create]

	def create
		@comment = Comment.new(comment_params)
		@comment.article_id = params[:article_id]

		@comment.save
		redirect_to article_path(@comment.article)
	end

	def comment_params
		params.require(:comment).permit(:author_name, :body)
	end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
before_filer :require_login, only: [:destroy]

	def index
		@tag = Tag.all
	end

	def show
		@tag = Tag.find(params[:id])
	end

	def destroy
		@tag = Tag.find(params[:id])
		@tag.delete

		flash.notice = "'#{@tag.name}' Has Been Deleted."
		redirect_to tags_path
	end

	def edit
		@tag = Tag.find(params[:id])
	end

	def update
		@tag = Tag.find(params[:id])
		@tag.update

		flash.notice = "'#{@tag.title}' Has Been Updated!"

		redirect_to tag_path(@tag)
	end
	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def article_params
		params.require(:article).permit(:title, :body, :tag_list, :image)
	end
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
	def tag_params
		params.require(:tags).permit(:tag_list)
	end
end

app/views/articles/_comment.html.erb
<div>
	<h4><%= comment.author_name %></h4>
	<p class="comment"><%= comment.body %></p>
	<p>Posted <%= distance_of_time_in_words(Time.now, comment.created_at) %> ago</p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
	<ul>
		<% @article.errors.full_messages do |error| %>
		<li><%= error %></li>
		<% end %>
	</ul>
	<p>
		<%= f.label :title %><br />
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :tag_list %><br />
		<%= f.text_field :tag_list %>
	</p>
	<p>
		<%= f.label :body %><br >
		<%= f.text_area :body %>
	</p>
	<p>
		<% if @article.image.exists? %>
			<%= image_tag @article.image.url(:medium) %><br />
		<% end %>
		<%= f.label :image, "Attach an Image(.jpg, .jpeg, .png)"%><b />
		<%= f.file_field :image %>
	</p>
	<p>
		<%= f.submit %>
	</p>
	<% end %>

app/views/articles/edit.html.erb
<h1>Edit</h1>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
	<% @article.each do |article| %>
	<li>
		<%= link_to article.title, article_path(article) %>
		</li>
	<% end %>
</ul>

<%= link_to "Create a new Article!", new_article_path, class: "new_article" %>

app/views/articles/new.html.erb
<h1>What's on your mind?</h1>
<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= image_tag @article.image.url (:medium)%></p>
<p><%= @article.body %></p>
<p>
	Tags:
	<% @article.tags.each do |tag| %>
	<%= link_to tag.name, tag_path(tag) %>
	<% end %>
</p>
<h3>Comments (<%= @article.comments.size %>)</h3>
<%= render partial: 'articles/comment', collection: @article.comments %>

<%= render partial: 'comments/form' %>

<%= link_to "<< Back to Articles List", articles_path %>

<% if logged_in? %>
<%= link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Are you sure?"} %>

<%= link_to "edit", edit_article_path(@article) %>

<% end %>

app/views/author_sessions/new.html.erb
<h1>Login</h1>
<%= form_tag author_sessions_path, method: :post do %>
	<div class="field">
		<%= label_tag :email %>
		<%= text_field_tag :email %>
		<br />
	</div>
	<div class = "field">
		<%= label_tag :password %>
		<%= password_field_tag :password %>
		<br />
	</div>
	<div class="actions">
		<%= submit_tag "Login" %>		
	</div>
	<% end %>

<%= link_to 'Back', articles_path %>

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Authors</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.username %></td>
        <td><%= author.email %></td>

        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @author.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>



<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/comments/_form.html.erb
<h3>What do you think?</h3>

<%= form_for [ @article, @comment ] do |f| %>
	<p>
		<%= f.label :author_name, "Name" %><br />
		<%= f.text_field :author_name %>
	</p>
	<p>
		<%= f.label :body, "Comment" %><br />
		<%= f.text_area :body %>
	</p>
	<p>
		<%= f.submit 'Submit' %>
	</p>
	<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="flash"><%= flash.notice %></p>
<div id = "container">
	<div id= "content">
		<%= yield %>
		<hr>
		<h6>
			<% if logged_in? %>
			<%= "Logged in as #{current_user.email}" %>
			<%= link_to "(logout)", logout_path %>
			<% else %>
			<%= link_to "(login)", login_path %>
			<%= link_to "Register", new_author_path %>
			<% end %>
		</h6>
		</div>
	</div>
</body>
</html>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
	<ul>
		<% @tag.errors.full_messages do |error| %>
		<li><%= error %></li>
		<% end %>
	</ul>
	<p>
		<%= f.label :tag_list %><br />
		<%= f.text_field :tag_list %>
	</p>

	<p>
		<%= f.submit %>
	</p>
	<% end %>

app/views/tags/edit.html.erb
<h1>Edit Tag</h1>
<%= render partial: 'tags/form' %>

app/views/tags/index.html.erb
<h1>Tags</h1>
<ul id="tags">
	<% @tag.each do |tag| %>
	<li>
		<%= link_to tag.name, tag %>

	</li>
	<% end %>
	
</ul>

<h3>Actions</h3>
<%= link_to "Back to Article List", articles_path %>

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
	<% @tag.articles.each do |article| %>
	<li><%= link_to article.title, article_path(article) %></li>
	<% end %>
</ul>

<%= link_to "Back to Tags List" , tags_path %>
<%= link_to "Delete Tag", tag_path(@tag), method: :delete, data: {confirm: "Are you sure?"} %>